#!/bin/bash


STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$")

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

PASS=false

printf "\nValidating PHPCS:\n"

# Check for phpcs
which ./vendor/bin/phpcs &> /dev/null
if [[ "$?" == 1 ]]; then
  printf "\t\033[41mPlease install PHPCS\033[0m"
  exit 1
fi

RULESET=./phpcs.xml

for FILE in $STAGED_FILES
do
  ./vendor/bin/phpcbf --standard="$RULESET" "$FILE"
  ./vendor/bin/phpcs --standard="$RULESET" "$FILE"

  if [[ "$?" == 0 ]]; then
    printf "\t\033[32mPHPCS Passed: $FILE\033[0m"
  else
    printf "\t\033[41mPHPCS Failed: $FILE\033[0m"
    PASS=true
  fi
done

printf "\nPHPCS validation completed!\n"

if ! $PASS; then
  printf "\n\033[42mCOMMIT SUCCEEDED\033[0m\n\n"
else
  printf "\n\033[42mCOMMIT SUCCEEDED\033[0m\n\n"
fi

exit $?
