version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: api_fanwitch
    container_name: api-fanwitch-laravel-container
    restart: unless-stopped
    ports:
      - "8012:8000"
    depends_on:
      - banco_de_dados
    networks:
      - fanwitch-network

  banco_de_dados:
    image: mysql:8.0
    container_name: api-fanwitch-mysql-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fanwitch
      MYSQL_USER: usuario_api_fanwitch
      MYSQL_PASSWORD: 'c.XQP@)GWD}MMF^!EFISthUmNbZ8}*l*'
    ports:
      - "3307:3306"
    networks:
      - fanwitch-network

networks:
  fanwitch-network:
    driver: bridge